lab6/imager/imager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

lab6/imager/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('slika/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('slika/<int:image_id>/upvote', views.upvote, name='upvote'),
    path('slika/<int:image_id>/upvote', views.downvote, name='downvote'),
]

lab6/imager/polls/models.py
from django.db import models

# Create your models here.

class Image(models.Model):
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=1000)
    pub_date= models.DateTimeField('date_published')
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Comment(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    comment = models.CharField(max_length=1000)
    pub_date = models.DateTimeField ('date_published')

    def __str__(self):
        return self.name

lab6/imager/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from polls.models import Image
from django.urls import reverse

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'image_list'

    def get_queryset(self):
        return Image.objects.all

class DetailView(generic.DetailView):
    template_name = 'polls/detail.html'
    model = Image

def upvote(request, image_id):
    image = get_object_or_404(Image, pk=image_id)
    image.votes += 1
    image.save()
    return HttpResponseRedirect(reverse('polls:index'))

def downvote(request, image_id):
    image = get_object_or_404(Image, pk=image_id)
    image.votes -= 1
    image.save()
    return HttpResponseRedirect(reverse('polls:index'))

lab6/imager/polls/templates/polls/detail.html
<h1>{{ image.name }}</h1>
<div style="width:100%;">
     <div style="width:60%;float:left;">
        <img src="{{ image.url }}" style="width:100%"/>
    </div>
    <div style ="width:30%;float:left">
        <p>Score: {{ image.votes }}</p>
        <form action = "{% url 'polls:upvote' image.id%}" method ="post">
            {% csrf_token %}
            <input type = "submit" value="LIKE">
        </form>
        <form action = "{% url 'polls:downvote' image.id%}" method ="post">
            {% csrf_token %}
            <input type = "submit" value="DISLIKE">
        </form>
        
    </div>
</div>

lab6/imager/polls/templates/polls/index.html
<h1>SLIKE</h1>

{% if image_list  %}
    <div style="width:100%">
    {% for image in image_list %}
        <div style="width:30%; float:left; padding:10px;">
        <p>{{ image.name }}
            <small>
                {{ image.pub_date}}
            </small>
        </p>
        <a href="{% url 'polls:detail' image.id %}">
            <img src= "{{image.url}}" style="width:100%; height: 50%;"/>
        </a>
    </div>
    {% endfor %}
    </div>
{% else %}
    <h3>Nema učitanih slika</h3>

{% endif %}